[workspace]
members = ["crates/*"]

[package]
name = "cyanocitta"
version = "0.0.0"
description = "A Nostr client"
authors = ["Jonas Mathisrud Sterud <jonas.sterud@gmail.com>"]
license = "MIT"
repository = "https://github.com/jonassterud/cyanocitta"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.0", features = [] }

[dependencies]
cyanocitta_nostr_tools = { version = "*", path = "crates/cyanocitta_nostr_tools" }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-alpha.0", features = ["fs-create-dir", "fs-read-file", "fs-write-file", "path-all", "shell-open"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
