[package]
name = "cyanocitta"
version = "0.0.0"
description = "A Nostr client"
authors = ["Jonas Mathisrud Sterud <jonas.sterud@gmail.com>"]
license = ""
repository = "https://github.com/jonassterud/fpt"
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2", features = ["shell-open"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
